### PR TITLE
Interface tricks

### PR DESCRIPTION
**Pull request by lukechampine**
I'm not sure if you're actively maintaining this package anymore, but I figured I'd contribute some tricks I picked up while working on my own low-level package, https://github.com/lukechampine/freeze.

### CODE REVIEW

**Comment by lukechampine** [comment]
Oh, looks like `reflect.ArrayOf` was not added until Go 1.5. I'll update this tomorrow to use `reflect.MakeSlice` instead.

**Comment by teh-cmc** [comment]
Ha, great! This has been in dire need of a massive spring-cleaning for quite some time now!
Thanks for your time, I'll check that as soon as I have a minute; I'm sure I'll learn some interesting hacks :>

(`freeze` looks nice btw, it certainly could have saved me some hair a few weeks ago... :weary:)

**Comment by lukechampine** [comment]
Apologies for deleting so much of your code lol.
btw, I tried to test `freetree` to confirm that I hadn't broken anything, but it panicked on both this branch and master.

**Comment by teh-cmc** [comment]
> Apologies for deleting so much of your code lol.

Haha, don't worry I was looking forward to doing just that, eventually; I owe you one!

> btw, I tried to test freetree to confirm that I hadn't broken anything, but it panicked on both this branch and master.

Yeeaaa weeell... those week-end-hack thingies all have this inexplicable habit of ending up panicking for no reason it seems... :stuck_out_tongue:

Seriously though, I'll try to take a look at that too; time is just quite scarce at the moment, unfortunately. :)

**Pull request merged**
